pupils = int(input("Введите колличество школьников: "))
apples = int(input("Введите колличество яблок: "))
res, cart = divmod(apples, pupils)
print("Каждому школьнику досталось яблок:", res, "шт.")
print("Яблок осталось в корзине:", cart, "шт.")
